# Generated by Django 4.1 on 2022-08-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srecalendarapp', '0002_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sre',
            name='id',
        ),
        migrations.AlterField(
            model_name='sre',
            name='sre_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
