# Generated by Django 4.1 on 2022-08-31 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srecalendarapp', '0003_remove_sre_id_alter_sre_sre_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_type',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='calendar_list',
            fields=[
                ('calendar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(max_length=200)),
                ('sre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srecalendarapp.sre')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srecalendarapp.list_type')),
            ],
        ),
    ]
