# Generated by Django 4.1 on 2022-09-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srecalendarapp', '0006_remove_offset_offset_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_list',
            name='sre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='srecalendarapp.sre'),
        ),
        migrations.AlterField(
            model_name='calendar_list',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='srecalendarapp.list_type'),
        ),
    ]
