# Generated by Django 4.1 on 2022-09-04 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srecalendarapp', '0007_alter_calendar_list_sre_alter_calendar_list_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offset',
            name='offset_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offset',
            name='offset_expiring',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offset',
            name='offset_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offset',
            name='offset_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offset',
            name='offset_used',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
