# Generated by Django 2.2 on 2022-09-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srecalendarapp', '0008_offset_offset_end_offset_offset_expiring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offset',
            name='offset_bal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offset',
            name='offset_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offset',
            name='offset_expiring',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='offset',
            name='offset_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='offset',
            name='offset_used',
            field=models.FloatField(),
        ),
    ]
