# Generated by Django 2.2 on 2022-09-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srecalendarapp', '0009_auto_20220906_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_start', models.DateTimeField(auto_now_add=True)),
                ('offset_end', models.DateTimeField(auto_now_add=True)),
                ('sre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srecalendarapp.sre')),
            ],
        ),
    ]
