# Generated by Django 2.2 on 2022-09-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srecalendarapp', '0010_datamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='offset',
            name='sre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srecalendarapp.sre'),
        ),
        migrations.DeleteModel(
            name='DataModel',
        ),
    ]
