# Generated by Django 2.2 on 2022-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srecalendarapp', '0012_auto_20220910_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offset',
            name='offset_used',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
