# Generated by Django 2.2 on 2022-09-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srecalendarapp', '0013_auto_20220911_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offset',
            name='offset_expiring',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
